import { AppProps } from 'next/app'
import Head from 'next/head'
import { ThemeProvider } from "next-themes";
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider enableSystem={true} attribute="class">
      <Head>
        <title>YJG30737</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      {/* import { Switch, Route } from 'react-router-dom';
      import routes from './routes';

      function App() {
        return (
          <div>
            <Navbar />
            <Switch>
              {routes.map((route) => (
                <Route key={route.path} path={route.path} exact={route.exact}>
                  <route.component />
                </Route>
              ))}
            </Switch>
          </div>
        );
      }

      export default App; */}
    </ThemeProvider>
  )
}

export default MyApp
